spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;
    username: sa

multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved